pipelineName: tidb-daily-pipeline 
repo: pingcap/tidb 
defaultRef: master 
triggers:
    crons:
    - cronString: "15 0 * * *" 
      defaultRef: "master"
tasks:
    - taskName: "tidb-build" 
      checkerName: "build-check" 
      params:  
        shellScript: |
            make
        outputDir: "bin/"
      retry: 1   
      timeout: 20 
      image: "hub.pingcap.net/jenkins/centos7_golang-1.18:latest"  
      resources:  
          requests:
              memory: "2000Mi"
              cpu: "1000m"
          limits:
              memory: "4000Mi"
              cpu: "2000m"

   
    - taskName: "tidb_ghpr_ingration_enterprise_plugin_test" 
      checkerName: "jenkins-it-trigger-check" 
      params: 
        itJobName: tidb_ghpr_ingration_enterprise_plugin_test
      timeout: 120 
      image: "hub.pingcap.net/jenkins/centos7_golang-1.18:latest"  
      resources:  
          requests:
              memory: "100Mi"
              cpu: "200m"
          limits:
              memory: "200Mi"
              cpu: "400m"
notify:
    lark: [purelind]
    email: [lifu.wu@pingcap.com]
