pipelineName: tidb-daily-pipeline 
repo: pingcap/tidb 
defaultRef: master 
triggers:
    crons:
    - cronString: "15 0 * * *" 
      defaultRef: "master"
tasks:
    - taskName: "tidb-build" 
      checkerName: "build-check" 
      params:  
        shellScript: |
            make
        outputDir: "bin/"
      retry: 1   
      timeout: 20 
      image: "hub.pingcap.net/jenkins/centos7_golang-1.18:latest"  
      resources:  
          requests:
              memory: "2000Mi"
              cpu: "1000m"
          limits:
              memory: "4000Mi"
              cpu: "2000m"

    - taskName: "tidb-gosec" 
      checkerName: "gosec-check" 
      params: 
        shellScript: |
            gosec -exclude-generated -fmt=junit-xml -out=results.xml -stdout -verbose=text -exclude=G103,G104,G204,G304,G307,G401,G404,G501,G505,G601 ./...
        reportDir: results.xml
      timeout: 60 
      image: "hub.pingcap.net/jenkins/centos7_golang-1.18:latest"  
      resources:  
          requests:
              memory: "20000Mi"
              cpu: "20000m"
          limits:
              memory: "32000Mi"
              cpu: "32000m"

    - taskName: "tidb-ut" 
      checkerName: "ut-cov-check" 
      params: 
        shellScript: |
            export log_level=warn
            mkdir -p coverage_report
            make br_unit_test_in_verify_ci || true
            mv test_coverage/br_cov.unit_test.out coverage_report/br.coverage || true
            make dumpling_unit_test_in_verify_ci || true
            mv test_coverage/dumpling_cov.unit_test.out coverage_report/dumpling.coverage || true
            make gotest_in_verify_ci || true
            mv test_coverage/tidb_cov.unit_test.out coverage_report/tidb.coverage || true
        utReport: test_coverage/*.xml
        covReport: coverage_report/*.coverage
        coverageRate: 50  
      timeout: 60 
      image: "hub.pingcap.net/jenkins/centos7_golang-1.18:latest"  
      resources:  
          requests:
              memory: "4000Mi"
              cpu: "2000m"
          limits:
              memory: "32000Mi"
              cpu: "16000m"
      credentials:
        - jenkinsID: codecov-token-tidb
          key: CODECOV_TOKEN
        - jenkinsID: codecov-api-token
          key: CODECOV_API_TOKEN
          
    - taskName: "tidb-lint" 
      checkerName: "lint-check" 
      params: 
        shellScript: |
            golangci-lint run --out-format=junit-xml -v ./... > golangci-lint-report.xml
        reportDir: golangci-lint-report.xml
      timeout: 60 
      image: "hub.pingcap.net/jenkins/centos7_golang-1.18:latest"  
      resources:  
          requests:
              memory: "16000Mi"
              cpu: "8000m"
          limits:
              memory: "32000Mi"
              cpu: "20000m"

notify:
    lark: [purelind]
    email: []
