pipelineName: tidb-daily-pipeline 
repo: pingcap/tidb 
defaultRef: master 
triggers:
    crons:
    - cronString: "15 0 * * *" 
      defaultRef: "master"
tasks:
    - taskName: "tidb-build" 
      checkerName: "build-check" 
      params:  
        shellScript: |
            make
        outputDir: "bin/"
      retry: 1   
      timeout: 20 
      image: "hub.pingcap.net/jenkins/centos7_golang-1.18:latest"  
      resources:  
          requests:
              memory: "2000Mi"
              cpu: "1000m"
          limits:
              memory: "4000Mi"
              cpu: "2000m"

   
    - taskName: "tidb-chain-bench" 
      checkerName: "common-check" 
      params: 
        shellScript: |
             /home/jenkins/chain-bench scan --repository-url https://github.com/pingcap/tidb --access-token ${CHAIN_BENCH_TOKEN} -o output.json
      timeout: 60 
      image: "hub.pingcap.net/jenkins/centos7_golang-1.18:chain-bench"
      credentials:
        - jenkinsID: chain-bench-token
          key: CHAIN_BENCH_TOKEN
      resources:  
          requests:
              memory: "8000Mi"
              cpu: "4000m"
          limits:
              memory: "8000Mi"
              cpu: "4000m"

notify:
    lark: [purelind]
    email: [lifu.wu@pingcap.com]
